version: "3.9"
name: "biblioteca"
services:
    php:
        container_name: "biblioteca-php"
        build:
            args:
                user: biblioteca
                uid: 1000
            context: ./
            dockerfile: .docker/php/Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - local

    nginx:
        container_name: "biblioteca-nginx"
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d/
            - ./.docker/nginx/.data/log:/var/log/nginx
        depends_on:
            - php
        networks:
            - local

    mysql:
        container_name: "biblioteca-mysql"
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: biblioteca
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - ./.docker/mysql/.data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - local

networks:
    local:
        driver: bridge
